config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  namespace 'v1' do
    resources :builds
    resources :items
  end

  get "/*path" => 'frontend#index'
  root to: 'frontend#index'
end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :items

  validates :url, presence: true
  validates_format_of :url, with: /(d3planner\.com\/[0-9]+|diablofans\.com\/builds\/[0-9]+\-)/i
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :builds
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :trackable, :omniauth_providers => [:bnet]
  has_many :builds

  class << self
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.battletag = auth.info.battletag
        user.blizzard_account_id = auth.info.id
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  layout 'frontend'

  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def bnet
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  def after_omniauth_failure_path_for(scope)
    redirect_to '/builds'
  end
end

app/controllers/v1/builds_controller.rb
require "uri"

module V1
  class BuildsController < ApplicationController
    before_action :set_build, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token
    respond_to :html, :json

    # GET /builds
    # GET /builds.json
    def index
      @builds = current_user.builds.all
    end

    # GET /builds/1
    # GET /builds/1.json
    def show
    end

    # GET /builds/new
    def new
      @build = Build.new
    end

    # GET /builds/1/edit
    def edit
    end

    # POST /builds
    # POST /builds.json
    def create
      @build = FetchBuildCommand.new.run(Build.new(build_params))
      @build.user = current_user

      respond_to do |format|
        if @build.save
          format.html { redirect_to @build, notice: 'Build was successfully created.' }
          format.json { render json: current_user.builds.all, status: :ok }
        else
          format.html { render :new }
          format.json { render json: @build.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /builds/1
    # PATCH/PUT /builds/1.json
    def update
      respond_to do |format|
        if @build.update(build_params)
          format.html { redirect_to @build, notice: 'Build was successfully updated.' }
          format.json { render :show, status: :ok, location: @build }
        else
          format.html { render :edit }
          format.json { render json: @build.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /builds/1
    # DELETE /builds/1.json
    def destroy
      @build.destroy
      respond_to do |format|
        format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
        format.json { render json: current_user.builds.all, status: :ok }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.permit(:title, :url)
    end
  end
end

app/controllers/v1/items_controller.rb
module V1
  class ItemsController < ApplicationController

    def index
      puts '='*20
      puts "Using BNET_KEY: #{ENV['BNET_KEY']}"
      puts "Using BNET_SECRET: #{ENV['BNET_SECRET']}"
      puts '='*20

      @items = Build.all.map(&:items).flatten.uniq
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def items_from_slot(items, slot)
    items.select{|item| item.data['slots'].include?(slot)}
  end
end

app/views/frontend/index.html.erb
<div id="content"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3collector</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <p>
  <% if current_user %>
    <%= link_to 'Logout', users_sign_out_path  %>
  <% else %>
    <%= link_to 'Login', user_omniauth_authorize_path(:bnet) %>
  <% end %>
  </p>

  <%= yield %>

  <script src="//us.battle.net/d3/static/js/tooltips.js"></script>
</body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <base href="/">
    <title>your app</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "index" %>
    <link rel="icon" href="./assets/images/favicon.png" type="image/png">
  </head>
  <body>
    <%= yield %>
    <script src="//us.battle.net/d3/static/js/tooltips.js"></script>
    <%= javascript_include_tag "main" %>
  </body>
</html>

app/views/v1/builds/_form.html.erb
<%= form_for @build, url: v1_build_path(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/v1/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form' %>

<%= link_to 'Show', v1_build_path(@build) %> |
<%= link_to 'Back', v1_builds_path %>

app/views/v1/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <%= binding.pry %>
      <tr>
        <td><%= build.title %></td>
        <td><%= build.url %></td>
        <td><%= link_to 'Show', v1_build_path(build) %></td>
        <td><%= link_to 'Edit', edit_v1_build_path(build) %></td>
        <td><%= link_to 'Destroy', v1_build_path(build), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_v1_build_path %>

app/views/v1/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form' %>

<%= link_to 'Back', v1_builds_path %>

app/views/v1/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @build.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @build.url %>
</p>

<p>
  <strong>Data:</strong>
  <%= @build.data %>
</p>

<p>
  <strong>Source:</strong>
  <%= @build.source %>
</p>

<p>
  <strong>Source ID:</strong>
  <%= @build.source_id %>
</p>

<p>
  <strong>Fetched At:</strong>
  <%= @build.fetched_at %>
</p>

<p>
  <strong>Items</strong>
  <ul>
  <% @build.items.each do |item| %>
    <li><%= item.blizzard_id %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_v1_build_path(@build) %> |
<%= link_to 'Back', v1_builds_path %>

app/views/v1/items/_slot_list.html.erb
<h3><%= title %></h3>
<ul>
  <% items_from_slot(items, slot).uniq.each do |item| %>
    <li>
      <%= link_to "//us.battle.net/d3/en/#{item.data['tooltipParams']}", class: "tooltip-link #{item.data['displayColor']}", onclick: 'return false' do %>
        <%= image_tag "http://us.media.blizzard.com/d3/icons/items/large/#{item.data['icon']}.png", height: 50 %>
        <span class='item-title'><%= item.data['name'] %></span>
        <span class='count'>(<%= pluralize(item.builds.count, 'build') %>)</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/v1/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<%= render partial: "slot_list", locals: {items: @items, title: 'Head', slot: 'head'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Shoulders', slot: 'shoulder'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Chest', slot: 'chest'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Belts', slot: 'waist'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Legs', slot: 'legs'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Gloves', slot: 'hands'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Bracers', slot: 'bracers'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Boots', slot: 'feet'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Amulets', slot: 'neck'} %>
<%= render partial: "slot_list", locals: {items: @items, title: 'Rings', slot: 'left-finger'} %>

<br />

<%= link_to 'New Build', new_v1_build_path %>